name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          ssh-strict: false
          script: |
            cd /var/www/quality-hub
            sudo chown -R admin:admin /var/www/quality-hub
            git pull
            sudo chown -R www-data:www-data /var/www/quality-hub
